name: Build telegram-rss-bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Set GOOS
        run: |
          echo ::set-env name=GOOS::$(go env GOOS)

      - name: Set GOARCH
        run: |
          echo ::set-env name=GOARCH::$(go env GOARCH)

      - name: Build telegram-rss-bot on ${{ matrix.os }}
        env:
          GOARCH: ${{ env.GOARCH }}
          GOOS: ${{ env.GOOS }}
        run: go build -o build/telegram-rss-bot-$GOARCH-$GOARCH

      - name: Test
        run: go test -v .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: build/